metadata:
  item_id: "portal"
  display_name: "Portal"
  category: "transport"

visuals:
  color: ""
  origin_point: "top_left"
  background:
    enabled: true
    display_mode: "stretch"
    offset_x: 0
    offset_y: 0
    states:
      normal:
        image_path: "Images/items_portals/portal_normal"
        file_type: "gif"
        frame_delay: 400

physics:
  occupy_width: 3
  occupy_height: 3
  is_collidable: false

logic:
  default_effects: []
  interaction_behavior: "teleport"
  charge_time: 1.0
  action_handler: "portal_logic"
  max_health: 0
  faction: "friendly"
  is_interactable: true
  is_invincible: true
