// =============================================================================
// AnimatedTexture.cs — Multi-frame animated texture (for GIF support)
//
// Loads individual frame PNGs (name_frame0.png, name_frame1.png, ...)
// generated by pixel_artify.py. Cycles through frames at a fixed interval.
// =============================================================================

using System.Collections.Generic;
using System.IO;
using Microsoft.Xna.Framework.Graphics;

namespace FarmGame.Core;

public class AnimatedTexture
{
    private readonly List<Texture2D> _frames = new();
    private readonly float _frameDelayMs;
    private float _timer;
    private int _currentIndex;

    public Texture2D CurrentFrame => _frames.Count > 0 ? _frames[_currentIndex] : null;
    public int FrameCount => _frames.Count;
    public bool IsAnimated => _frames.Count > 1;

    public AnimatedTexture(float frameDelayMs = 150f)
    {
        _frameDelayMs = frameDelayMs;
    }

    public void AddFrame(Texture2D frame)
    {
        _frames.Add(frame);
    }

    public void Update(float deltaTimeSeconds)
    {
        if (_frames.Count <= 1) return;

        _timer += deltaTimeSeconds * 1000f;
        if (_timer >= _frameDelayMs)
        {
            _timer -= _frameDelayMs;
            _currentIndex = (_currentIndex + 1) % _frames.Count;
        }
    }

    /// <summary>
    /// Load frame PNGs from a directory: baseName_frame0.png, baseName_frame1.png, ...
    /// </summary>
    public static AnimatedTexture LoadFrames(
        GraphicsDevice graphicsDevice, string contentDir,
        string imagePath, float frameDelayMs = 150f)
    {
        var anim = new AnimatedTexture(frameDelayMs);

        for (int i = 0; ; i++)
        {
            var framePath = Path.Combine(contentDir, imagePath + $"_frame{i}.png");
            if (!File.Exists(framePath)) break;

            using var stream = File.OpenRead(framePath);
            var tex = Texture2D.FromStream(graphicsDevice, stream);
            anim.AddFrame(tex);
        }

        return anim;
    }
}
